"use client";

import type React from "react";

import { createContext, useContext, useEffect, useState } from "react";

type LanguageContextType = {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState("en");
  const [translations, setTranslations] = useState<
    Record<string, Record<string, string>>
  >({});

  useEffect(() => {
    // Load translations from local storage or set default
    const storedLang = localStorage.getItem("language") || "en";
    setLanguage(storedLang);

    // Load translation files
    const loadTranslations = async () => {
      try {
        const enTranslations = {
          "common.home": "Home",
          "common.search": "Search",
          "common.login": "Login",
          "common.register": "Register",
          "common.logout": "Logout",
          "common.profile": "Profile",
          "common.settings": "Settings",
          "common.darkMode": "Dark Mode",
          "common.lightMode": "Light Mode",
          "common.language": "Language",
          "common.readMore": "Read More",
          "common.loading": "Loading...",
          "common.error": "Error",
          "common.retry": "Retry",
          "common.save": "Save",
          "common.cancel": "Cancel",
          "common.submit": "Submit",
          "common.delete": "Delete",
          "common.edit": "Edit",
          "common.filter": "Filter",
          "common.sort": "Sort",
          "common.genre": "Genre",
          "common.status": "Status",
          "common.rating": "Rating",
          "common.author": "Author",
          "common.artist": "Artist",
          "common.publisher": "Publisher",
          "common.releaseDate": "Release Date",
          "common.chapter": "Chapter",
          "common.chapters": "Chapters",
          "common.volume": "Volume",
          "common.volumes": "Volumes",
          "common.page": "Page",
          "common.pages": "Pages",
          "common.next": "Next",
          "common.previous": "Previous",
          "common.first": "First",
          "common.last": "Last",
          "common.readNow": "Read Now",
          "common.continue": "Continue",
          "common.start": "Start",
          "common.finish": "Finish",
          "common.random": "Random",
          "common.popular": "Popular",
          "common.trending": "Trending",
          "common.new": "New",
          "common.updated": "Updated",
          "common.completed": "Completed",
          "common.ongoing": "Ongoing",
          "common.hiatus": "Hiatus",
          "common.cancelled": "Cancelled",
          "common.all": "All",
          "common.more": "More",
          "common.less": "Less",
          "common.show": "Show",
          "common.hide": "Hide",
          "common.enable": "Enable",
          "common.disable": "Disable",
          "common.on": "On",
          "common.off": "Off",
          "common.yes": "Yes",
          "common.no": "No",
          "common.ok": "OK",
          "common.apply": "Apply",
          "common.reset": "Reset",
          "common.clear": "Clear",
          "common.close": "Close",
          "common.open": "Open",
          "common.add": "Add",
          "common.remove": "Remove",
          "common.create": "Create",
          "common.update": "Update",
          "common.view": "View",
          "common.details": "Details",
          "common.summary": "Summary",
          "common.description": "Description",
          "common.information": "Information",
          "common.comments": "Comments",
          "common.reviews": "Reviews",
          "common.ratings": "Ratings",
          "common.likes": "Likes",
          "common.dislikes": "Dislikes",
          "common.favorites": "Favorites",
          "common.bookmarks": "Bookmarks",
          "common.history": "History",
          "common.recommendations": "Recommendations",
          "common.similar": "Similar",
          "common.related": "Related",
          "common.categories": "Categories",
          "common.tags": "Tags",
          "common.keywords": "Keywords",
          "common.topics": "Topics",
          "common.themes": "Themes",
          "common.demographics": "Demographics",
          "common.content": "Content",
          "common.warning": "Warning",
          "common.adult": "Adult",
          "common.mature": "Mature",
          "common.explicit": "Explicit",
          "common.safe": "Safe",
          "common.suggestive": "Suggestive",
          "common.erotica": "Erotica",
          "common.pornographic": "Pornographic",
          "common.gore": "Gore",
          "common.violence": "Violence",
          "common.sexual": "Sexual",
          "common.nudity": "Nudity",
          "common.drugs": "Drugs",
          "common.alcohol": "Alcohol",
          "common.smoking": "Smoking",
          "common.gambling": "Gambling",
          "common.suicide": "Suicide",
          "common.selfHarm": "Self Harm",
          "common.depression": "Depression",
          "common.anxiety": "Anxiety",
          "common.ptsd": "PTSD",
          "common.trauma": "Trauma",
          "common.abuse": "Abuse",
          "common.discrimination": "Discrimination",
          "common.racism": "Racism",
          "common.sexism": "Sexism",
          "common.homophobia": "Homophobia",
          "common.transphobia": "Transphobia",
          "common.xenophobia": "Xenophobia",
          "common.religious": "Religious",
          "common.political": "Political",
          "common.controversial": "Controversial",
          "common.offensive": "Offensive",
          "common.disturbing": "Disturbing",
          "common.triggering": "Triggering",
          "common.sensitive": "Sensitive",
          "common.spoiler": "Spoiler",
          "common.spoilers": '  "Sensitive',

          // Auth related
          "auth.login": "Login",
          "auth.register": "Register",
          "auth.logout": "Logout",
          "auth.email": "Email",
          "auth.password": "Password",
          "auth.username": "Username",
          "auth.name": "Name",
          "auth.confirmPassword": "Confirm Password",
          "auth.forgotPassword": "Forgot Password",
          "auth.resetPassword": "Reset Password",
          "auth.rememberMe": "Remember Me",
          "auth.alreadyHaveAccount": "Already have an account?",
          "auth.dontHaveAccount": "Don't have an account?",
          "auth.signIn": "Sign In",
          "auth.signUp": "Sign Up",
          "auth.signOut": "Sign Out",
          "auth.profile": "Profile",
          "auth.settings": "Settings",
          "auth.avatar": "Avatar",
          "auth.birthDate": "Birth Date",
          "auth.adultContent": "Adult Content",
          "auth.enableAdultContent": "Enable Adult Content",
          "auth.disableAdultContent": "Disable Adult Content",

          // Manga related
          "manga.title": "Title",
          "manga.alternativeTitles": "Alternative Titles",
          "manga.description": "Description",
          "manga.genres": "Genres",
          "manga.tags": "Tags",
          "manga.status": "Status",
          "manga.releaseDate": "Release Date",
          "manga.publisher": "Publisher",
          "manga.author": "Author",
          "manga.artist": "Artist",
          "manga.chapters": "Chapters",
          "manga.volumes": "Volumes",
          "manga.rating": "Rating",
          "manga.popularity": "Popularity",
          "manga.readingStatus": "Reading Status",
          "manga.reading": "Reading",
          "manga.onHold": "On Hold",
          "manga.planToRead": "Plan to Read",
          "manga.dropped": "Dropped",
          "manga.reReading": "Re-reading",
          "manga.completed": "Completed",
          "manga.readNow": "Read Now",
          "manga.continueReading": "Continue Reading",
          "manga.addToLibrary": "Add to Library",
          "manga.removeFromLibrary": "Remove from Library",
          "manga.like": "Like",
          "manga.unlike": "Unlike",
          "manga.comment": "Comment",
          "manga.comments": "Comments",
          "manga.reviews": "Reviews",
          "manga.recommendations": "Recommendations",
          "manga.similar": "Similar Manga",
          "manga.related": "Related Manga",
          "manga.random": "Random Manga",
          "manga.featured": "Featured Manga",
          "manga.popular": "Popular Manga",
          "manga.trending": "Trending Manga",
          "manga.new": "New Manga",
          "manga.updated": "Updated Manga",
          "manga.ongoing": "Ongoing Manga",
          "manga.hiatus": "Hiatus Manga",
          "manga.cancelled": "Cancelled Manga",

          // Reader related
          "reader.chapter": "Chapter",
          "reader.volume": "Volume",
          "reader.page": "Page",
          "reader.pages": "Pages",
          "reader.next": "Next",
          "reader.previous": "Previous",
          "reader.first": "First",
          "reader.last": "Last",
          "reader.loading": "Loading...",
          "reader.error": "Error loading chapter",
          "reader.retry": "Retry",
          "reader.settings": "Settings",
          "reader.autoScroll": "Auto Scroll",
          "reader.speed": "Speed",
          "reader.direction": "Direction",
          "reader.mode": "Mode",
          "reader.fitWidth": "Fit Width",
          "reader.fitHeight": "Fit Height",
          "reader.originalSize": "Original Size",
          "reader.zoomIn": "Zoom In",
          "reader.zoomOut": "Zoom Out",
          "reader.resetZoom": "Reset Zoom",
          "reader.fullscreen": "Fullscreen",
          "reader.exitFullscreen": "Exit Fullscreen",
          "reader.infiniteScroll": "Infinite Scroll",
          "reader.pagination": "Pagination",
          "reader.webtoon": "Webtoon",
          "reader.leftToRight": "Left to Right",
          "reader.rightToLeft": "Right to Left",
          "reader.verticalScroll": "Vertical Scroll",
          "reader.horizontalScroll": "Horizontal Scroll",
        };

        const ruTranslations = {
          "common.home": "Главная",
          "common.search": "Поиск",
          "common.login": "Вход",
          "common.register": "Регистрация",
          "common.logout": "Выход",
          "common.profile": "Профиль",
          "common.settings": "Настройки",
          "common.darkMode": "Темная тема",
          "common.lightMode": "Светлая тема",
          "common.language": "Язык",
          "common.readMore": "Читать далее",
          "common.loading": "Загрузка...",
          "common.error": "Ошибка",
          "common.retry": "Повторить",
          "common.save": "Сохранить",
          "common.cancel": "Отмена",
          "common.submit": "Отправить",
          "common.delete": "Удалить",
          "common.edit": "Редактировать",
          "common.filter": "Фильтр",
          "common.sort": "Сортировка",
          "common.genre": "Жанр",
          "common.status": "Статус",
          "common.rating": "Рейтинг",
          "common.random": "Случайная манга",
          "common.popular": "Популярное",
          "common.trending": "В тренде",
          "common.new": "Новое",
          "common.updated": "Обновлено",
          "common.more": "Больше",

          // Manga related
          "manga.title": "Название",
          "manga.description": "Описание",
          "manga.genres": "Жанры",
          "manga.tags": "Теги",
          "manga.status": "Статус",
          "manga.author": "Автор",
          "manga.chapters": "Главы",
          "manga.readNow": "Читать",
          "manga.continueReading": "Продолжить чтение",
          "manga.addToLibrary": "Добавить в библиотеку",
          "manga.random": "Случайная манга",
          "manga.featured": "Рекомендуемая манга",
          "manga.popular": "Популярная манга",
          "manga.updated": "Обновленная манга",
        };

        const uzTranslations = {
          "common.home": "Bosh sahifa",
          "common.search": "Qidirish",
          "common.login": "Kirish",
          "common.register": "Ro'yxatdan o'tish",
          "common.logout": "Chiqish",
          "common.profile": "Profil",
          "common.settings": "Sozlamalar",
          "common.darkMode": "Qorong'i rejim",
          "common.lightMode": "Yorug' rejim",
          "common.language": "Til",
          "common.readMore": "Ko'proq o'qish",
          "common.loading": "Yuklanmoqda...",
          "common.error": "Xato",
          "common.retry": "Qayta urinish",
          "common.save": "Saqlash",
          "common.cancel": "Bekor qilish",
          "common.random": "Tasodifiy manga",
          "common.popular": "Mashhurlar",
          "common.genre": "Taglar",
          "common.new": "Yangi",
          "common.updated": "Yangilangan",
          "common.more": "Ko'proq",

          // Manga related
          "manga.title": "Sarlavha",
          "manga.description": "Tavsif",
          "manga.genres": "Janrlar",
          "manga.genre": "Janrlar",
          "manga.tags": "Teglar",
          "manga.status": "Holat",
          "manga.author": "Muallif",
          "manga.chapters": "Boblar",
          "manga.readNow": "Hozir o'qish",
          "manga.continueReading": "O'qishni davom ettirish",
          "manga.addToLibrary": "Kutubxonaga qo'shish",
          "manga.random": "Tasodifiy manga",
          "manga.featured": "Tavsiya etilgan manga",
          "manga.popular": "Mashhur manga",
          "manga.updated": "Yangilangan manga",
        };

        setTranslations({
          en: enTranslations,
          ru: ruTranslations,
          uz: uzTranslations,
        });
      } catch (error) {
        console.error("Failed to load translations:", error);
      }
    };

    loadTranslations();
  }, []);

  // Save language preference to local storage when it changes
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  // Translation function
  const t = (key: string): string => {
    if (!translations[language]) return key;
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
